name: Release Assets

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.4.0

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build

      - name: Pack
        run: npm pack

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "readable-regexp ${{ github.ref }}"
          prerelease: false
          files: *.tgz

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          dry-run: true
          token: ${{ secrets.NPM_TOKEN }}